/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData office_08 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData office_25 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData office_61 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bible = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData fish_jesus_fisherman = const IconData(0xe807, fontFamily: _kFontFam);
}
