/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData thumb_down = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bible = const IconData(0xf100, fontFamily: _kFontFam);
  static const IconData open_pdf_booklet = const IconData(0xf101, fontFamily: _kFontFam);
  static const IconData open_booklet = const IconData(0xf102, fontFamily: _kFontFam);
  static const IconData notebook = const IconData(0xf103, fontFamily: _kFontFam);
}
